server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.39.160:3306/eco_assignment_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/hr-schema-mysql.sql
decorator:
  datasource:
    p6spy:
      enable-logging: true

open-api:
  enkey: mS8eocglDCoWXFZygs0nKhgM8bKalgCaaNjt%2FnCsK2UX36vwt%2Fb%2FVAcrciN7RIJOGc5zMPOr9ZP1nElUTbVAqA%3D%3D
  dekey: mS8eocglDCoWXFZygs0nKhgM8bKalgCaaNjt/nCsK2UX36vwt/b/VAcrciN7RIJOGc5zMPOr9ZP1nElUTbVAqA==

  url: https://www.daegufood.go.kr/kor/api/Alley.html?mode=json